authors/urls.py
from django.urls import path
from authors.views import register_view, register_create, login_create, \
                    login_view, logout_view, dashboard, dashboard_receita_edit, \
                    dashboard_receita_new, dashboard_receita_delete

from authors.views_class import DashboardReceita, DashboardReceitaDelete


app_name = 'authors'

urlpatterns = [
    path('register/', register_view, name= 'register'),
    path('register/create/', register_create, name= 'register_create'),
    path('login/', login_view, name= 'login'),
    path('login/create/', login_create, name= 'login_create'),
    path('logout/', logout_view, name='logout'),
    path('dashboard/', dashboard, name='dashboard'),
    #path('dashboard/recipe/new/', dashboard_receita_new, name='dashboard_receita_new'),
    path('dashboard/recipe/new/', DashboardReceita.as_view(), name='dashboard_receita_new'),
    #path('dashboard/receita/delete/', dashboard_receita_delete, name='dashboard_receita_delete'),
    path('dashboard/receita/delete/', DashboardReceitaDelete.as_view(), name='dashboard_receita_delete'),
    #path('dashboard/receita/<int:id>/edit/', dashboard_receita_edit, name='dashboard_receita_edit'),
    path('dashboard/receita/<int:id>/edit/', DashboardReceita.as_view(), name='dashboard_receita_edit'),
]

project/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('receitas.urls')),
    path('authors/', include('authors.urls')),
] 

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

templates/global/partials/footer.html
<footer class="fixed-bottom main-footer">
    <div class="developer">
      <a href="https://www.otaviomiranda.com.br/" target="_blank" rel="noreferrer noopener">Gilmar Dalla Nora</a>
    </div>
  
    <div class="powered">
      <a href="https://www.djangoproject.com/" target="_blank" rel="noreferrer noopener">Desenvolvido em Django</a>
    </div>
  </footer>

templates/global/partials/form.html
<div class="main-content container">
  <form class="main-form" action="{{ form_action }}" method="POST" enctype="multipart/form-data">
    {% csrf_token %}

    <div class="form-content form-content-grid">
      {% for field in form %}
      <div class="form-group {{ field.field.widget.attrs.class }}">
        <label for="{{ field.id_for_label }}">{{ field.label }}</label>
        {{field}}

        {% if field.help_text %}
          <p class="help-text">{{ field.help_text }}</p>
        {% endif %}

        {{ field.errors }}
      </div>
      {% if field.name == 'cover' and field.value.url %}
      <div class="span-2">
        <img src="{{ field.value.url }}" alt="Capa para {{ recipe.title }}">
      </div>
      {% endif %}

      {% endfor %}
    </div>

    {% if form.errors %}
    <div class="form-content form-content-grid">
      <div class="form-group">
        <div class="message message-error">
          Há erros no formulário, corrija-os e envie novamente.
        </div>
      </div>
    </div>
    {% endif %}
    <div class="form-content form-content-grid">
      <div class="form-group">
        <button type="submit">Enviar</button>
      </div>
    </div>
  </form>
</div>

templates/global/partials/head.html
{% load static %}
<!DOCTYPE html>
<html lang="pt-BR">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.4/css/fontawesome.min.css"
        integrity="sha512-P9vJUXK+LyvAzj8otTOKzdfF1F3UYVl13+F8Fof8/2QNb8Twd6Vb+VD52I7+87tex9UXxnzPgWA3rH96RExA7A=="
        crossorigin="anonymous" referrerpolicy="no-referrer" />
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.4/css/brands.min.css"
        integrity="sha512-sVSECYdnRMezwuq5uAjKQJEcu2wybeAPjU4VJQ9pCRcCY4pIpIw4YMHIOQ0CypfwHRvdSPbH++dA3O4Hihm/LQ=="
        crossorigin="anonymous" referrerpolicy="no-referrer" />
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.4/css/solid.min.css"
        integrity="sha512-tk4nGrLxft4l30r9ETuejLU0a3d7LwMzj0eXjzc16JQj+5U1IeVoCuGLObRDc3+eQMUcEQY1RIDPGvuA7SNQ2w=="
        crossorigin="anonymous" referrerpolicy="no-referrer" />
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Roboto+Slab:wght@900&display=swap" rel="stylesheet">

    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css">

    <link rel="stylesheet" href="{% static 'global/css/styles.css' %}">
    <link rel="stylesheet" href="{% static 'global/css/global-style.css' %}">


    

    <title>
        {% block titulo %} {% endblock titulo %}
    </title>
</head>

templates/global/partials/header.html
<header class="main-header-container">
    <div class="main-header container">
        <h1>
            <a class="main-logo" href="{% url 'receitas-home' %}">
                
               
                
                <span class="main-logo-text">  Bolzan Veiculos  </span>
            </a>
        </h1>
    </div>
</header>

templates/global/partials/menu.html
<button class="button-show-menu button-show-menu-visible">
    <i class="fas fa-bars"></i>
    <span class="hidden-text">Mostrar menu</span>
  </button>
  
  <div class="menu-container menu-hidden">
    <button class="button-close-menu button-close-menu-visible">
      <i class="fas fa-times-circle"></i>
      <span class="hidden-text">Fechar menu</span>
    </button>
  
    <div class="menu-content">
      <nav class="menu-nav">
       
        <a>Usuario ({{ user.username }})</a>
        <a href="{% url 'receitas-home' %}">Home</a>
  
        {% if user.is_authenticated %}
          <a href="{% url 'authors:dashboard' %}">Suas receita</a>
          <a href="{% url 'authors:dashboard_receita_new' %}">Nova receita</a>
          {% comment %} <a href="{% url 'authors:dashboard' %}">Painel</a> {% endcomment %}
          <a class="authors-logout-link" href="{% url 'authors:logout' %}">Sair</a>
        {% include 'authors/partials/form_logout.html' %}
        {% else %}
          <a href="{% url 'authors:login' %}">Entrar</a>
          <a href="{% url 'authors:register' %}">Registrar</a>
      {% endif %}
      </nav>
    </div>
  </div>

templates/global/partials/messages.html
{% if messages %}
<div class="main-content center container messages-container">
    
    {% for message in messages %}
        <div class="message {{ message.tags }}">
            {{ message }}
        </div>
    {% endfor %}
</div>
{% endif %}

templates/global/partials/pagination.html
{% if receitas.has_other_pages %}
  <div class="container pagination">
    <div class="pagination-content">
      {% if pagination_range.first_page_out_of_range %}
        <a class="page-link page-item" href="?page=1" {{ additional_url_query }}>1</a>
        <span class="page-item">...</span>
      {% endif %}

      {% for page in pagination_range.pagination %}
        {% if pagination_range.current_page == page  %}
          <a class="page-link page-item page-current" href="?page={{ page }}{{ additional_url_query }}">{{ page }}</a>
        {% else %}
        <a class="page-link page-item" href="?page={{ page }}{{ additional_url_query }}">{{ page }}</a>
        {% endif %}
      {% endfor %}

      {% if pagination_range.last_page_out_of_range %}
        <span class="page-item">...</span>
        <a class="page-link page-item" href="?page={{ pagination_range.total_pages }}{{ additional_url_query }}">{{ pagination_range.total_pages }}</a>
      {% endif %}    
    </div>
  </div>
{% endif %}

templates/global/partials/search.html
<div class="search-container">
    <div class="container">
        <form action="{% url 'receitas-search' %}" method="GET" class="search-form">
            <input type="search" class="search-input" name="q" value="{{ search_term }}" required>
            <button type="submit" class="search-button"><i class="fas fa-search"></i></button>
        </form>
    </div>
</div>